- purl: pkg:deb/ubuntu/helm@1.9.1-1?arch=source&distro=xenial
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@1.9.2-1?arch=source&distro=xenial
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@2.8.2-1?arch=source&distro=bionic
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@2.8.5-1?arch=source&distro=bionic
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@2.8.6-1?arch=source&distro=bionic
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@2.8.7-1?arch=source&distro=bionic
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@2.8.8-1?arch=source&distro=bionic
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@3.2-1?arch=source&distro=focal
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@3.5.0-3?arch=source&distro=focal
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@3.6.0-1?arch=source&distro=focal
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@3.7.0-2?arch=source&distro=jammy
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@3.8.0-1?arch=source&distro=jammy
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@3.8.4-1?arch=source&distro=noble
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@3.8.4-2?arch=source&distro=questing
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/helm@4.0.3-1?arch=source&distro=questing
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
  fixing_vulnerabilities: []
