- purl: pkg:deb/ubuntu/golang-github-prometheus-exporter-toolkit@0.5.1-2?arch=source&distro=jammy
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-46146
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/golang-github-prometheus-exporter-toolkit@0.7.0-1?arch=source&distro=jammy
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-46146
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/golang-github-prometheus-exporter-toolkit@0.7.0-2?arch=source&distro=jammy
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-46146
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/golang-github-prometheus-exporter-toolkit@0.7.1-1?arch=source&distro=jammy
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-46146
  fixing_vulnerabilities: []
- purl: pkg:deb/ubuntu/golang-github-prometheus-exporter-toolkit@0.7.1-1ubuntu1?arch=source&distro=jammy
  affected_by_vulnerabilities:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-46146
  fixing_vulnerabilities: []
